version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./Proyecto_adri.sql:/Proyecto_adri.sql
    ports:
      - "3306:3306"
