DROP DATABASE IF EXISTS LAS_CARMELITAS ;

CREATE DATABASE LAS_CARMELITAS ;

USE LAS_CARMELITAS ; 

CREATE TABLE Ciclo_Escolar 
	(
MATERNAL INT (10),
JARDÍN INT (10),
PREESCOLAR INT (10),
PRIMARIA INT (10),
SECUNDARIA INT (10),
PRIMARY KEY (Administracion)
)
;

CREATE TABLE Alumnos
	(
NOMBRE  VARCHAR (40), 
APELLIDO VARCHAR (40), 
ID_LEGAJO int primary key not null, 
DOMICILIO VARCHAR (60), 
TELEFONO VARCHAR (15),
ANIO_INGRESO YEAR 
PRIMARY KEY (Ciclo_Escolar) INT NOT NULL, 
FK_PADRES INT NOT NULL,
FOREIGN KEY (FK_PADRES) REFERENCES PADRES  
) 
;  

CREATE TABLE Docentes 
	(
NOMBRE VARCHAR (40), 
APELLIDO VARCHAR (40), 
ID_LEGAJO int (20), 
TITULO VARCHAR (100), 
DOMICILIO VARCHAR (60), 
TELEFONO VARCHAR (15),
EMAIL VARCHAR (100), 
MATERIA VARCHAR (30),
HORARIO TIME
) 
;  

CREATE TABLE Padres
	(
NOMBRE VARCHAR (40),
APELLIDO VARCHAR (40), 
-- LEGAJO HIJOS Acá quisiera vincular la información de los hijos con los padres
OCUPACION VARCHAR (30),
DOMICILIO VARCHAR (60), 
TELEFONO VARCHAR (15)
) 
;  

CREATE TABLE Administracion
	(
PAGOS INT (20),
COBRANZAS INT (20),
PRIMARY KEY (ID_LEGAJO)
)
;

CREATE TABLE Pagos
	(
PROVEEDORES VARCHAR (100) NOT NULL,
SERVICIOS VARCHAR (60),
HABERES INT (9),
COB_MEDICA VARCHAR (20),
SEGUROS DECIMAL (20,3)
)
;

CREATE TABLE Cobranzas
	(
CUOTA INT (65),
MATRICULA INT (60),
MICRO INT (9),
COMEDOR INT (20)
)
;
